AppBundle\Entity\Identificaciones:
    type: entity
    table: identificaciones
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
    lifecycleCallbacks: {  }
