AppBundle\Entity\Refrendos:
    type: entity
    table: refrendos
    indexes:
        iddatosgenerales:
            columns:
                - iddatosgenerales
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        abonocapital:
            type: integer
            nullable: true
            options:
                unsigned: false
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        estado:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fechapagado:
            type: datetime
            nullable: true
        fechavencimiento:
            type: datetime
            nullable: true
        interes:
            type: integer
            nullable: true
            options:
                unsigned: false
        observaciones:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        recargo:
            type: integer
            nullable: true
            options:
                unsigned: false
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
    manyToOne:
        iddatosgenerales:
            targetEntity: Datosgenerales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iddatosgenerales:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
